Description:
    This templates deploys compute resrouces for a high-avilability web app in AWS

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
  ASGMinSize:
    Description: Mininum number of servers in Auto Scaling Group
    Type: String
  ASGMaxSize:
    Description: Maxinum number of servers in Auto Scaling Group
    Type: String
  ASGDesiredSize:
    Description: Desired number of servers in Auto Scaling Group
    Type: String

Resources:

# Security Groups
  myLB-SG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http traffic to LB
      SecurityGroupEgress: 
        - InProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
        - InProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId:
        Fn::ImportValue:
          !Sub "${EnviromentName}-VPCID"
      Tags: 
        - Key: Name
          Value: !Sub "${EnviromentName}-LB"
  myWebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http traffic to the host and SSH locally
      SecurityGroupEgress: 
        - InProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress: 
        - InProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - InProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId:
        Fn::ImportValue:
          !Sub "${EnviromentName}-VPCID"
      Tags: 
        - Key: Name
          Value: !Sub "${EnviromentName}-LB"

# Auto Scaling Group
  myWebAppLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://tirgan-hawa/hawa.zip .
          unzip -o hawa.zip
      ImageId: ami-005bdb005fb00e791
      KeyName: automation
      IamInstanceProfile: !Ref HawaInstance
      SecurityGroups:
      - Ref: myWebServerSG
      InstanceType: t2.micro
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
  
  myWebAppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue:
          !Sub "${EnviromentName}-PRIV-NETS"
      LaunchConfiguration: !Ref myWebAppLaunchConfiguration
      MinSize: !Ref ASGMinSize
      MaxSize: !Ref ASGMaxSize
      DesiredCapacity: !Ref ASGDesiredSize
      TargetGroupARNs: !Ref myWebAppTargetGroup

  myWebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:


